resolver: lts-7.16
packages:
- location:
   git: https://github.com/jonascarpay/convoluted.git
   commit: c3627fd273d6d0e1ce77306de99a86f0b95ab2bd
  extra-dep: true
- '.'

extra-deps: []
flags: {}
extra-package-dbs: []
